### ISSUE TITLE
Relicense to MIT/APL-2.0

### ISSUE THREAD

**Issue by l1npengtul** [l1npengtul/nokhwa#11]
I currently want to change the license to MIT/APL2 for integration with `nannou`. For this I require your signatures.
Sorry for the ping. 

Reply with "I agree" or something similar to indicate that you are okay with this change.

- [x] @kuy 
- [x] @valeth 
- [x] @joshua-maros

**Comment by someguynamedjosh** [comment]
I agree

**Comment by kuy** [comment]
I agree.

**Comment by valeth** [comment]
I agree

**Comment by l1npengtul** [comment]
Thank you!
