### ISSUE TITLE
Access Violation Error on Windows 10

### ISSUE THREAD

**Issue by alvindev0** [l1npengtul/nokhwa#13]
I'm having this issue with the latest stable release (0.7.0) on Windows 10.

Here is my dependency in `Cargo.toml`:
```
nokhwa = { version = "0.7.0", features = ["input-msmf"] }
```

Here is the error I'm getting when running the example code:
```
C:\msmf-test>cargo run
   Compiling msmf-test v0.0.1 (C:\msmf-test)
    Finished dev [unoptimized + debuginfo] target(s) in 1.14s
     Running `target\debug\msmf-test.exe`
error: process didn't exit successfully: `target\debug\msmf-test.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

I have tried running the application as admin and allowed app access to my webcam through control panel.

**Comment by l1npengtul** [comment]
Try with 0.8, I have fixed the access violation bug and it works on my machine.

**Comment by alvindev0** [comment]
Issue has been fixed. Thank you.
