### ISSUE TITLE
what FrameFormat::GRAY is?

### ISSUE THREAD

**Issue by yamt** [l1npengtul/nokhwa#158]
right now, the avfoundation binding maps FrameFormate::GRAY to kCMPixelFormat_8IndexedGray_WhiteIsZero.
kCMPixelFormat_8IndexedGray_WhiteIsZero seems to mean, as its name suggests, 0 -> white, 255 -> black.
is it what FrameFormat::GRAY means?

anyway, i guess FrameFormat should have precise bit-level definitions on each formats.

**Comment by l1npengtul** [comment]
Yes, its a grayscale u8.
I will make it more clear in 0.11.
