### ISSUE TITLE
Build failed when I used OpenCV

### ISSUE THREAD

**Issue by xgpxg** [l1npengtul/nokhwa#183]
When I enable feature "input-opencv", it can not build，`new_rows_cols_with_data` function  args not match. Mybe the OpenCV version is incorrect, or for other reasons?
 
![image](https://github.com/user-attachments/assets/868765c8-1e15-47cf-adb7-d691025d708b)
![image](https://github.com/user-attachments/assets/0ab9a264-d1ac-45e3-b107-ea794189806e)

error code in: nokhwa-core-0.1.3\src\buffer.rs:140:24
nokhwa: 0.10.5
open-cv: 0.93

**Comment by l1npengtul** [comment]
Oh sorry, I must have not updated the function signature properly. I'll work on a fix.

**Comment by maniema4real** [comment]
The error is still there :-)
nokhwa:0.10.5
opencv:0.93.4

**Comment by l1npengtul** [comment]
Builds with OpenCV on latest commit. Open new issue if you find more problems. Thank you for reporting! 0.10.5 will be out soon.
