### ISSUE TITLE
crates.io publish request

### ISSUE THREAD

**Issue by darioalessandro** [l1npengtul/nokhwa#186]
Hello @l1npengtul :

Thank you for building this awesome tool! 

I want to release `video-call-daemon` to crates.io 
Link: https://github.com/security-union/videocall-rs/pull/176

```
This is a rust application that can be used to connect to the video call daemon and stream video to a meeting.
```

I depend on the latest commit of https://github.com/l1npengtul/nokhwa/tree/0.10

Would you kindly publish this crate to crates.io so that I can release?

Thanks

Dario

**Comment by l1npengtul** [comment]
I will test it tonight and release very soon. Please keep tuned for 0.11!

**Comment by darioalessandro** [comment]
well, thank you my friend 😄 based on your super fast response very soon means a few days?

**Comment by l1npengtul** [comment]
Probably, although macos will be a "maybe" (no mac machine)

**Comment by darioalessandro** [comment]
I can volunteer to test. I have 4 macbook computers at your service:

2 intel: i5 and i7
2 arm: M1 and M2

How can I help you to validate the crate? Would you have an integration test?

![image](https://github.com/user-attachments/assets/6f1dda19-c3d8-4058-9eda-38f09335c443)

**Comment by darioalessandro** [comment]
How are things looking? you mentioned that macos might be the blocker, can I help you with that?

**Comment by darioalessandro** [comment]
Hey @l1npengtul how are things looking?

**Comment by l1npengtul** [comment]
> Hey @l1npengtul how are things looking? 

please give me a little bit of time... school is starting to get busy 😔

**Comment by l1npengtul** [comment]
0.10.6 published, closing.

**Comment by darioalessandro** [comment]
@l1npengtul thank you so much!!!
