### ISSUE TITLE
Only get last frame, ignoring missed frames

### ISSUE THREAD

**Issue by tqwewe** [l1npengtul/nokhwa#30]
I'm making an app with nannou, but my webcam gets lagged behind quite a bit when my drawing cannot keep up with it's framerate.

Is there a way to get only the latest frame available, and ignore any other frames that might've been missed?

**Comment by l1npengtul** [comment]
May I see some example code? 
You may be interested in [last_frame()](https://docs.rs/nokhwa/0.9.4/nokhwa/struct.ThreadedCamera.html#method.last_frame).

**Comment by tqwewe** [comment]
Thanks for the fast reply, that's exactly what I wanted! Thanks 👍
