### ISSUE TITLE
how to close or release a camera

### ISSUE THREAD

**Issue by zhusihan-python** [l1npengtul/nokhwa#32]
hello, i have 2 camera on my win10,  i found they can not open at the same time, it will block infinitely, is there a way to release a camera like in opencv cap.release(), how to switch the camera in nokhwa

**Comment by l1npengtul** [comment]
You may be interested in [`Camera::stop_stream`](https://docs.rs/nokhwa/latest/nokhwa/struct.Camera.html#method.stop_stream)
