### ISSUE TITLE
convert the captured frames into OpenCV mat

### ISSUE THREAD

**Issue by ke-aidi** [l1npengtul/nokhwa#33]
How to convert the captured frames into OpenCV mat? 
Some examples will be ideal.

**Comment by l1npengtul** [comment]
Try converting the slice to a 2D slice by height, collecting it into an `&[&[RGB]]` then using `Mat::from_slice_2d`. 

This will be built in behavior for 0.10

**Comment by l1npengtul** [comment]
Fixed 090c2bf764cf542288ed6ddd6c987a5c0b37be5c
