### ISSUE TITLE
How to enumerate compatible formats of a camera index

### ISSUE THREAD

**Issue by aleokdev** [l1npengtul/nokhwa#37]
Hello! I have a webcam of unknown parameters and I'd like to have a list of its supported formats and resolutions. How can you achieve that with the crate? I see there's [`compatible_camera_formats`](https://docs.rs/nokhwa/latest/nokhwa/struct.Camera.html#method.compatible_camera_formats), but to call it you need a `Camera` already constructed. I can't construct it because I don't know the format I need to provide. What should I do? (BTW: I'm only using the v4l backend)

**Comment by aleokdev** [comment]
Constructing a camera with `None` doesn't always work, as the default parameters don't seem to work with *every* webcam model.

**Comment by l1npengtul** [comment]
This is being worked on in 0.10.
