### ISSUE TITLE
UnsupportedOperatorError on query_devices

### ISSUE THREAD

**Issue by ogxd** [l1npengtul/nokhwa#50]
Hello, I am having an `UnsupportedOperatorError` when I call `query_device`. The error has no internal message. I tried with the Auto backend and then on several other backends but I ended up having the same error everytime.

```rust
match nokhwa::query_devices(nokhwa::CaptureAPIBackend::Auto) {
    Ok(cameras) => {
        // Never gets here
    },
    Err(err) => {
        // Always an error
    }
}
```

![image](https://user-images.githubusercontent.com/12692438/178722055-8e5467ce-dcd6-47af-a73e-6aa7e791e99e.png)

- Version used: nokhwa 0.9.4
- OS: Windows 11 x64
- Dell XPS 15" from 2020

Any idea of what could go wrong?

**Comment by l1npengtul** [comment]
Did you enable `input-msmf`?

**Comment by ogxd** [comment]
No! Just saw this 🤦 
> The default feature includes nothing. Anything starting with input-* is a feature that enables the specific backend. As a general rule of thumb, you would want to keep at least input-uvc or other backend that has querying enabled so you can get device information from nokhwa.

It works as excepted now!

Maybe for others that don't take the time to read everything it could be interesting to put a message in the error mentionning that there are no backends?

**Comment by l1npengtul** [comment]
Glad it worked out, I'll consider it for 0.10
