### ISSUE TITLE
input-msmf fails to detect camera on windows

### ISSUE THREAD

**Issue by sayanarijit** [l1npengtul/nokhwa#53]
Hi, first of all, thanks for the awesome library. I published a project using this library: https://github.com/sayanarijit/qrscan which runs fine on Linux.

However, as [reported by a windows user](https://github.com/sayanarijit/qrscan/issues/7), it fails to detect the camera on windows.

I am using `input-msmf` for the windows build.

The error is:

```
error: qrscan: Could not get device property Devices: Not Found
```

Device info:

![image](https://user-images.githubusercontent.com/11632726/180039125-d04a9548-52b3-4aca-94a9-4b224b95f239.png)

**Comment by l1npengtul** [comment]
The screenshot attached is useless, please ask the user to provide the model of the webcam they are using,

**Comment by Ginkooo** [comment]
I'm having the same issue too, on some windows 8 few years old asus (Asus R556 Series, some default driver)

**Comment by l1npengtul** [comment]
@Ginkooo have you tried changing your camera settings? Some cameras don't support YUYV/MJPEG, etc. I am working to fix this.

**Comment by sayanarijit** [comment]
>  have 3 DirectShow webcams: [GoPro Webcam](https://community.gopro.com/s/article/GoPro-Webcam), OBS Virtual Camera, and [NVIDIA Broadcast](https://www.nvidia.com/en-us/geforce/broadcasting/broadcast-app/). And I have the [ManyCam Virtual Webcam](https://help.manycam.com/knowledge-base/webcam-driver/) for use in UWP applications.

> In a similar case, I have tried [zbar](https://github.com/mchehab/zbar) from MSYS2, and the ManyCam Virtual Webcam worked.

**Comment by l1npengtul** [comment]
I honestly do not know why it doesn't work, I followed the Microsoft Documentation to a tee. Perhaps the camera just doesn't support MSMF.
