### ISSUE TITLE
cargo build failed

### ISSUE THREAD

**Issue by fly2moon2** [l1npengtul/nokhwa#58]
Hi,

I failed to build the cargo.  Various errors relating to CameraFormat emerge (see trace below).  Appreciate for any advice and enlightenment.  Thanks a lot!

....
   Compiling nokhwa-core v0.1.0 (/Users/jack/dev/spaces/ruspaces/gitz/gitzlib/camera/nokhwa/nokhwa-core)
warning: unused import: `std::borrow::Cow`
  --> nokhwa-core/src/buffer.rs:26:5
   |
26 | use std::borrow::Cow;
   |     ^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

error[E0271]: type mismatch resolving `<Filter<std::vec::IntoIter<CameraFormat>, [closure@nokhwa-core/src/types.rs:47:29: 47:78]> as Iterator>::Item == &_`
    --> nokhwa-core/src/types.rs:48:22
     |
48   |                     .copied()
     |                      ^^^^^^ expected reference, found struct `CameraFormat`
     |
     = note: expected reference `&_`
                   found struct `CameraFormat`
note: required by a bound in `copied`
    --> /Users/jack/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:3189:32
     |
3189 |         Self: Sized + Iterator<Item = &'a T>,
     |                                ^^^^^^^^^^^^ required by this bound in `copied`

error[E0599]: the method `collect` exists for struct `Copied<Filter<std::vec::IntoIter<CameraFormat>, [closure@nokhwa-core/src/types.rs:47:29: 47:78]>>`, but its trait bounds were not satisfied
  --> nokhwa-core/src/types.rs:49:22
   |
49 |                     .collect::<Vec<CameraFormat>>();
   |                      ^^^^^^^ method cannot be called on `Copied<Filter<std::vec::IntoIter<CameraFormat>, [closure@nokhwa-core/src/types.rs:47:29: 47:78]>>` due to unsatisfied trait bounds
   |
  ::: /Users/jack/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/adapters/copied.rs:17:1
   |
17 | pub struct Copied<I> {
   | -------------------- doesn't satisfy `_: Iterator`
   |
  ::: /Users/jack/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/adapters/filter.rs:15:1
   |
15 | pub struct Filter<I, P> {
   | ----------------------- doesn't satisfy `<_ as Iterator>::Item = &_`
   |
   = note: the following trait bounds were not satisfied:
           `<Filter<std::vec::IntoIter<CameraFormat>, [closure@nokhwa-core/src/types.rs:47:29: 47:78]> as Iterator>::Item = &_`
           which is required by `Copied<Filter<std::vec::IntoIter<CameraFormat>, [closure@nokhwa-core/src/types.rs:47:29: 47:78]>>: Iterator`
           `Copied<Filter<std::vec::IntoIter<CameraFormat>, [closure@nokhwa-core/src/types.rs:47:29: 47:78]>>: Iterator`
           which is required by `&mut Copied<Filter<std::vec::IntoIter<CameraFormat>, [closure@nokhwa-core/src/types.rs:47:29: 47:78]>>: Iterator`

error[E0308]: mismatched types
  --> nokhwa-core/src/types.rs:66:68
   |
66 |                         let dist_no_sqrt = (x_diff.abs()).pow(2) + (y_diff.abs()).pow(2) as u32;
   |                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `u32`

error[E0277]: cannot add `u32` to `i32`
  --> nokhwa-core/src/types.rs:66:66
   |
66 |                         let dist_no_sqrt = (x_diff.abs()).pow(2) + (y_diff.abs()).pow(2) as u32;
   |                                                                  ^ no implementation for `i32 + u32`
   |
   = help: the trait `Add<u32>` is not implemented for `i32`
   = help: the following other types implement trait `Add<Rhs>`:
             <&'a f32 as Add<f32>>
             <&'a f64 as Add<f64>>
             <&'a i128 as Add<i128>>
             <&'a i16 as Add<i16>>
             <&'a i32 as Add<i32>>
             <&'a i64 as Add<i64>>
             <&'a i8 as Add<i8>>
             <&'a isize as Add<isize>>
           and 48 others

error[E0277]: a value of type `Vec<(u32, Resolution)>` cannot be built from an iterator over elements of type `(i32, Resolution)`
    --> nokhwa-core/src/types.rs:69:22
     |
69   |                     .collect::<Vec<(u32, Resolution)>>();
     |                      ^^^^^^^ value of type `Vec<(u32, Resolution)>` cannot be built from `std::iter::Iterator<Item=(i32, Resolution)>`
     |
     = help: the trait `FromIterator<(i32, Resolution)>` is not implemented for `Vec<(u32, Resolution)>`
     = help: the trait `FromIterator<T>` is implemented for `Vec<T>`
note: required by a bound in `collect`
    --> /Users/jack/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1788:19
     |
1788 |     fn collect<B: FromIterator<Self::Item>>(self) -> B
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `collect`

error[E0614]: type `u32` cannot be dereferenced
  --> nokhwa-core/src/types.rs:70:55
   |
70 |                 resolution_map.sort_by(|a, b| a.0.cmp(*b.0));
   |                                                       ^^^^

error[E0277]: the trait bound `CameraFormat: Ord` is not satisfied
  --> nokhwa-core/src/types.rs:21:11
   |
16 | #[derive(Copy, Clone, Debug, Hash, Ord, PartialOrd, Eq, PartialEq)]
   |                                    --- in this derive macro expansion
...
21 |     Exact(CameraFormat),
   |           ^^^^^^^^^^^^ the trait `Ord` is not implemented for `CameraFormat`
   |
   = note: this error originates in the derive macro `Ord` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider annotating `CameraFormat` with `#[derive(Ord)]`
   |
301| #[derive(Ord)]
   |

error[E0277]: the trait bound `CameraFormat: Ord` is not satisfied
  --> nokhwa-core/src/types.rs:22:13
   |
16 | #[derive(Copy, Clone, Debug, Hash, Ord, PartialOrd, Eq, PartialEq)]
   |                                    --- in this derive macro expansion
...
22 |     Closest(CameraFormat),
   |             ^^^^^^^^^^^^ the trait `Ord` is not implemented for `CameraFormat`
   |
   = note: this error originates in the derive macro `Ord` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider annotating `CameraFormat` with `#[derive(Ord)]`
   |
301| #[derive(Ord)]
   |

error[E0277]: the trait bound `CameraFormat: Eq` is not satisfied
   --> nokhwa-core/src/types.rs:21:11
    |
16  | #[derive(Copy, Clone, Debug, Hash, Ord, PartialOrd, Eq, PartialEq)]
    |                                                     -- in this derive macro expansion
...
21  |     Exact(CameraFormat),
    |           ^^^^^^^^^^^^ the trait `Eq` is not implemented for `CameraFormat`
    |
note: required by a bound in `AssertParamIsEq`
   --> /Users/jack/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/cmp.rs:317:31
    |
317 | pub struct AssertParamIsEq<T: Eq + ?Sized> {
    |                               ^^ required by this bound in `AssertParamIsEq`
    = note: this error originates in the derive macro `Eq` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider annotating `CameraFormat` with `#[derive(Eq)]`
    |
301 | #[derive(Eq)]
    |

Some errors have detailed explanations: E0271, E0277, E0308, E0599, E0614.
For more information about an error, try `rustc --explain E0271`.
warning: `nokhwa-core` (lib) generated 1 warning
error: could not compile `nokhwa-core` due to 9 previous errors; 1 warning emitted

**Comment by l1npengtul** [comment]
0.10 is not yet finished. Compiler errors are to be expected. Please use 0.9.4 from crates.io.
