### ISSUE TITLE
Can't find attribute MF_MT_FRAME_RATE_RANGE_MAX on Windows Media Foundation

### ISSUE THREAD

**Issue by ghost** [l1npengtul/nokhwa#66]
I have some code that works great with my external webcam. However, my internal laptop webcam panics when nokhwa attempts to obtain the MF_MT_FRAME_RATE_RANGE_MAX attribute from wmf. The exact code where the issue originates is below in the screenshot.

![image](https://user-images.githubusercontent.com/19521402/199780633-4bd25cf8-bdb3-40bf-b455-98ce2aa7edc5.png)

![image](https://user-images.githubusercontent.com/19521402/199781338-312823ab-775f-41e0-b262-9ad0f4e04b2c.png)

I don't know what you need to know from this. I'm happy to help support by contributing code fixes myself... but I've never really interfaced with unsafe code or really anything like this.

Again, when I plug in my usb external webcam and target that device id, nokhwa grabs it just fine and can stream frames. I've double-checked that Windows Media Player is already installed as a OS feature. Help!

**Comment by l1npengtul** [comment]
sounds like i should add some guards... thanks for reporting.

**Comment by l1npengtul** [comment]
Fixed. Now function will not fail if it can't find a minimum. It will ignore it instead.
