### ISSUE TITLE
Error building latest commit with msmf

### ISSUE THREAD

**Issue by Thespyinthehole** [l1npengtul/nokhwa#67]
The latest commit does not compile correctly with msmf feature enable.

To fix, `fourcc` needs to become `guid` on line 171 in [lib.rs](https://github.com/l1npengtul/nokhwa/blob/senpai/nokhwa-bindings-windows/src/lib.rs), as well as `frame_rate_min` being changed to `frame_rate` in the same file.

**Comment by l1npengtul** [comment]
Thanks for reporting!
