### ISSUE TITLE
`Camera::frame_format` reports as `NV12` despite actually being `YUV422`

### ISSUE THREAD

**Issue by gennyble** [l1npengtul/nokhwa#78]
This is on my Macbook Air M1

The Camera reports as NV12, even after calling `refresh_camera_format`, despite actually being `YUYV`. If I stick a `println!("{}", received.1)` in `avfoundation.rs`'s `frame_raw` it correctly identifies it.

**Comment by l1npengtul** [comment]
This is already fixed on my local branch, but I am experiencing AVFoundation weirdness right now so I'll push it when its ready.
