### ISSUE TITLE
fourcc for grayscale

### ISSUE THREAD

**Issue by wegmarken2006** [l1npengtul/nokhwa#93]
Hello, 
fourcc for grayscale should be "GREY" instead of "GRAY".

**Comment by l1npengtul** [comment]
The difference between GRAY and GREY is reginal (american vs british)

I do not see a reason to change this, it conveys the message fine.

In future versions this will be called Luma, but for now there is no reason to change this.

**Comment by wegmarken2006** [comment]
I was not talking about the name used in the FrameFormat enum, which of course can be anything; I was talking about the string that is actually sent to the OS like in the write() below:
`
            FrameFormat::GRAY => {
                write!(f, "GRAY")
            }
`
 I don't know if I am missing something, I am using a yocto built linux, and the string "GRAY" is not recognized, see also https://www.kernel.org/doc/html/v4.10/media/uapi/v4l/pixfmt-grey.html

**Comment by l1npengtul** [comment]
We don't follow convention of a single platform. FrameFormat is nokhwa's own way of handling 4CCs, and we don't plan on word for word compatibility with v4l2
